title : 课外
lang  : zh
description : 课堂内外，丰富多彩
copyright : © 2022 - 2024 kewai All Rights Reserved
member :
  - github : ke-wai
user :
  - name : Yibo

nav :
  - name  : 文章
    link  : /
  - name  : 关于
    link  : /about.html